version: '3.7'
services:
  mysql:
    container_name: mysql-container
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
      - MYSQL_DATABASE=persons_register
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    ports:
      - "3306:3306"
  
  app:
    container_name: app-container
    restart: always
    build: ./
    working_dir: /srv/run
    volumes:
      - .:/srv/run
    ports:
      - "8080:8080"
    depends_on:
      - mysql
